apiVersion: v1
kind: Namespace
metadata:
  name: resume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-site
  namespace: resume
  labels:
    app: resume-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-site
  template:
    metadata:
      labels:
        app: resume-site
    spec:
      containers:
      - name: resume-site
        image: jaanuk/resume-site:v0.0.1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: resume-site
  namespace: resume
spec:
  selector:
    app: resume-site
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

